### ISSUE TITLE
Allow to specify port for --httpProxy and --httpsProxy command options

### ISSUE THREAD

**Issue by Huppys** [crossbrowsertesting/cbt-tunnel-nodejs#20]
Hi,

I'm trying to establish a connection to use crossbrowsertesting locally with the following command:
````
.\cbt_tunnels.exe --username USERNAME --authkey AUTHKEY --httpsProxy proxy.host:8080 --httpProxy proxy.host:8080 --acceptAllCerts
````

The output (with error) I get is:
````
[2019-04-24T14:31:55.270] [INFO] default - HTTP proxy set to proxy.host:8080
[2019-04-24T14:31:55.275] [INFO] default - HTTPS proxy set to proxy.host:8080
[2019-04-24T14:31:57.578] [ERROR] default - Authentication error! Please check your credentials and try again.
[2019-04-24T14:31:57.580] [ERROR] default - { Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 8080 8080:80
    at ClientRequest.onError (C:\snapshot\warner.johnson\Documents\CBT\cbt-tunnel-nodejs\node_modules\tunnel-agent\index.js:177:17)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
````

Would be nice to be able to specify an alternative port for the proxy.

**Comment by Gozke** [comment]
Hi @Huppys,
It's probably not relevant anymore.. but I had the same issue. Turns out it's possible (now) to specify the proxy port without an additional argument. You simple have to specify a full url including the scheme and the port.
The below command line ended up working for me on Windows:

`cbt_tunnels-win-x64.exe --verbose --httpProxy http://proxy.myorganization.xyz:1234 --username myUserId --authkey myAuthkey`

Ps.:
I haven't tried, but I'm assuming this way it would also be possible to provide credentials needed to access the proxy server.
